---
title: "Collaborator Analysis"
format: html
author: Ingrid Slette
---

## Exercise: Explore, Clean, and Wrangle Data

### Set up
```{r}
#| warning: false
#| message: false
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

### Read data
```{r}
#| warning: false
#| message: false
lobster_traps <- read_csv("../data/Lobster_Trap_Counts_All_Years_20210519.csv")
```

### Explore data
```{r}
colnames(lobster_traps)
glimpse(lobster_traps)
head(lobster_traps)
unique(lobster_traps$YEAR)
unique(lobster_traps$SITE)
unique(lobster_traps$TRAPS)
```

### Clean data
```{r}
lobster_traps <- lobster_traps %>% 
    mutate(TRAPS = na_if(TRAPS, -99999))
unique(lobster_traps$TRAPS)
```

### Create subset without NAPL site
```{r}
not_napl <- lobster_traps %>% 
    filter(SITE != "NAPL")
```

### Create subset with data from CARP or number of floats > 20
```{r}
carp_20_traps <- lobster_traps %>% 
    filter(SITE == "CARP" | TRAPS > 20)
```

## Exercise: Data Visualization
```{r}
#| message: false
#| warning: false
lobsters_traps_summarize <- lobster_traps %>% 
  group_by(SITE, YEAR) %>% 
  summarize(TOTAL_TRAPS = sum(TRAPS, na.rm = TRUE))
```

```{r}
# line and point plot
ggplot(data = lobsters_traps_summarize, aes(x = YEAR, y = TOTAL_TRAPS)) +
    geom_point(aes(color = SITE)) +
    geom_line(aes(color = SITE)) +
    labs(x = "Year", 
       y = "Total Trap Count",
       color = "Site",
       title = "Lobster Trap Counts Over Time",
       subtitle = "Total number of traps by site each year") +
  theme_bw() +
  scale_y_continuous(breaks = seq(0, 2100, 250)) +
  scale_color_viridis_d()
```
```{r}
#| message: false
#| warning: false
lobster_traps_fishing_pressure <- lobster_traps %>% 
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(FISHING_PRESSURE = if_else(TRAPS >= 8, true = "high", false = "low")) %>%
    group_by(SITE, FISHING_PRESSURE) %>%
    summarize(COUNT = n()) %>%
    drop_na()
```

```{r}
# dodged bar plot
ggplot(data = lobster_traps_fishing_pressure, aes(x = SITE, y = COUNT, fill = FISHING_PRESSURE)) +
    geom_col(position = "dodge") +
  labs(x = "Year", 
       y = "Count",
       fill = "Fishing Pressure",
       title = "Lobster Trap Counts",
       subtitle = "Total number of traps counts by site") +
  coord_flip() +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.ticks.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 650, 100))
```

